#!/bin/bash

#SBATCH --job-name=llm_launcher_small
#SBATCH --time=08:00:00
#SBATCH --account=tra26_bbs
#SBATCH --partition=boost_usr_prod
#SBATCH --qos=normal
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --cpus-per-task=32
#SBATCH --gres=gpu:4
#SBATCH --error llm_launcher_small-%j.err
#SBATCH --output llm_launcher_small-%j.out
#SBATCH --reservation=s_tra_bbs4

#################################################################
### Script to launch a containerized version of RAY and vllm. ###
################################################################

# API Token used by vllm to secure the requests. Eventually, this could be randomized.
API_TOKEN="password"
MODEL_PATH="mistralai/Mistral-Small-3.2-24B-Instruct-2506"

# Singularity container path
IMAGE_NAME="vllm-v0_17_0.img"
IMAGE_PATH="/leonardo_scratch/large/userinternal/rmioli00/public/container_images/$IMAGE_NAME"

# nccl configuration
export NCCL_IB_HCA="mlx5"           # RDMA interfaces to use for communication
export NCCL_SOCKET_IFNAME="ib0"     # IP interfaces to use for communication
#export NCCL_DEBUG=INFO
export VLLM_LOGGING_LEVEL=INFO
export HF_HUB_OFFLINE="1"
export HF_HOME="/leonardo_scratch/large/userinternal/rmioli00/public/models/hub"
export HF_HUB_CACHE="/leonardo_scratch/large/userinternal/rmioli00/public/models/hub"
export PYTHONNOUSERSITE=1

# Get the worker list associated to this slurm job
worker_list=($(scontrol show hostnames "$SLURM_JOB_NODELIST"))

# Set the first worker as the head node and get his ip
head_node=${worker_list[0]}
head_node_ip=$(srun --nodes=1 --ntasks=1 -w "$head_node" hostname --ip-address)
headnode_ip_ib_address=$(srun --nodes=1 --ntasks=1 -w "$head_node" ip -4 addr show ib0 | awk '/inet / {print $2}' | cut -d/ -f1)
echo [INFO]: Starting head node $head_node at $head_node_ip. Infiniband address is $headnode_ip_ib_address.

# Create overlay for the head node
echo [INFO]: Removing old headnode overlay and creating a new writable layer
OVERLAY_PATH="${SCRATCH}/worker_overlay_0.img"
rm $OVERLAY_PATH
singularity overlay create --sparse --size 16000 $OVERLAY_PATH

# Define commands to be runned on the nodes
ray_start_head_command="ray start --head --port=6379 --num-cpus $SLURM_CPUS_PER_TASK --num-gpus $SLURM_GPUS_ON_NODE --disable-usage-stats --block"
vllm_serve_command="vllm serve $MODEL_PATH --host 0.0.0.0 --port 8000 --tensor-parallel-size $SLURM_GPUS_ON_NODE --pipeline-parallel-size $SLURM_JOB_NUM_NODES --api-key $API_TOKEN --distributed-executor-backend ray --enable-auto-tool-choice --tool-call-parser mistral"
singularity_start_command="singularity exec --nv --bind /leonardo_scratch:/leonardo_scratch,/leonardo_work:/leonardo_work --overlay $OVERLAY_PATH $IMAGE_PATH bash -c"

# Run the commands. Note that ntasks in srun is set to 1 because otherwise the ray start command would be executing ntasks times, effectively spawning ntasks*--num-cpus workers.
echo [INFO]: srun --nodes=1 --ntasks=1 -w $head_node $singularity_start_command "$ray_start_head_command & sleep 30 && ray status && $vllm_serve_command"
srun --nodes=1 --ntasks=1 -w $head_node $singularity_start_command "$ray_start_head_command & sleep 30 && ray status && $vllm_serve_command" &

# Print ssh tunnel instructions
# Ray web ui is not included in the default vllm image.
# For that you will need to build a custom image
#echo ===================================================
#echo [INFO]: To access the RAY web ui, remember to open a ssh tunnel with:
#echo ssh -L 8265:$head_node_ip:8265 ${USER}@login02-ext.leonardo.cineca.it -N
#echo then you can connect to the dashboard at http://127.0.0.1:8265
#echo ===================================================
echo [INFO]: To access VLLM, remember to open a ssh tunnel with:
echo ssh -L 8000:$head_node_ip:8000 ${USER}@login02-ext.leonardo.cineca.it -N
echo then you can query the model at http://127.0.0.1:8000
echo ===================================================

# Start the workers
worker_num=$((SLURM_JOB_NUM_NODES - 1))

for ((i = 1; i <= worker_num; i++)); do
    worker_node_i=${worker_list[$i]}
    worker_node_ip=$(srun --nodes=1 --ntasks=1 -w $worker_node_i hostname --ip-address)
    worker_ip_ib_address=$(srun --nodes=1 --ntasks=1 -w $worker_node_i ip -4 addr show ib0 | awk '/inet / {print $2}' | cut -d/ -f1)

    echo [INFO]: Removing old workernode ${i} overlay and creating a new writable layer
    OVERLAY_PATH="${SCRATCH}/worker_overlay_${i}.img"
    rm $OVERLAY_PATH
    singularity overlay create --sparse --size 16000 $OVERLAY_PATH

    # Define commands to be runned on the worker node
    ray_start_worker_command="ray start --address $head_node_ip:6379 --num-cpus $SLURM_CPUS_PER_TASK --num-gpus $SLURM_GPUS_ON_NODE --disable-usage-stats --block"
    singularity_start_command="singularity exec --nv --bind /leonardo_scratch:/leonardo_scratch,/leonardo_work:/leonardo_work --overlay $OVERLAY_PATH $IMAGE_PATH bash -c"

    echo [INFO]: Starting worker $i $worker_node_i at $worker_node_ip. Infiniband address is $worker_ip_ib_address.
    echo [INFO]: srun --nodes=1 --ntasks=1 -w $worker_node_i $singularity_start_command "$ray_start_worker_command"
    srun --nodes=1 --ntasks=1 -w $worker_node_i $singularity_start_command "$ray_start_worker_command" &
done

echo [INFO]: everything is running.

sleep infinity
